name: Build wheels and release them into PYPI

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - VERSION
      - setup.py

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install requirements
        run: python3 -m pip install setuptools wheel twine

      - name: Build wheels
        run: python3 setup.py bdist_wheel

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verify-metadata: true
          skip-existing: true
          packages-dir: dist
          repository-url: https://upload.pypi.org/legacy/
          verbose: true
